# Generated by Django 4.0.2 on 2022-02-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_comment_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_posted']},
        ),
    ]
